version: "3.6"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local


services:
    redis:
        image: 'redis:5.0.5'
        command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow


    ################################################################################
    ## Spark cluster 
    ################################################################################
    ## spark master container
    spark-master:
        image: spark-master
        container_name: spark-master
        ports:
          - 8080:8080
          - 7077:7077
          - 4043:4040
        volumes:
          - ./data:/usr/local/airflow/data
          - ./mnt/scripts:/usr/local/airflow/scripts
          - ./output:/opt/output
  
    ## spark worker container
    spark-worker-1:
        image: spark-worker
        container_name: spark-worker-1
        environment:
          - SPARK_WORKER_CORES=1
          #- SPARK_WORKER_MEMORY=512m
        ports:
          - 8081:8081
        volumes:
          - ./data:/usr/local/airflow/data
          - ./mnt/scripts:/usr/local/airflow/scripts
          - ./output:/opt/output
        depends_on:
            - spark-master

    ## spark worker container
    spark-worker-2:
        image: spark-worker
        container_name: spark-worker-2
        environment:
          - SPARK_WORKER_CORES=1
          #- SPARK_WORKER_MEMORY=512m
        ports:
          - 8082:8081
        volumes:
          - ./data:/usr/local/airflow/data
          - ./mnt/scripts:/usr/local/airflow/scripts
          - ./output:/opt/output
        depends_on:
            - spark-master

